-- Составьте список пользователей users, которые осуществили хотя бы один заказ orders в интернет магазине.

use shop;

SELECT users.id, users.name 
FROM users
JOIN orders
ON users.id = orders.user_id;


-- Выведите список товаров products и разделов catalogs, который соответствует товару.

SELECT p.name AS 'Товар', c.name AS 'Группа в каталоге'
FROM products AS p
LEFT JOIN catalogs AS c
ON p.catalog_id = c.id
ORDER BY p.name;


-- (по желанию) Пусть имеется таблица рейсов flights (id, from, to) и таблица городов cities (label, name).
-- Поля from, to и label содержат английские названия городов, поле name — русское. Выведите список рейсов flights с русскими названиями городов.

DROP TABLE IF EXISTS flights;
CREATE TABLE flights (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'Идентификатор строки',
  from_place VARCHAR(255) COMMENT 'Точка отбытия',
  to_place VARCHAR(255) COMMENT 'Точка прибытия'
);

DROP TABLE IF EXISTS cities;
CREATE TABLE cities (
  label VARCHAR(255) COMMENT 'Название города на английском',
  name VARCHAR(255) COMMENT 'Название города на русском'
);

INSERT INTO cities  (label, name) VALUES
("Abakan", "Абакан"),
("Almetyevsk", "Альметьевск"),
("Anadyr", "Анадырь"),
("Anapa", "Анапа"),
("Arkhangelsk", "Архангельск"),
("Astrakhan", "Астрахань"),
("Barnaul", "Барнаул"),
("Belgorod", "Белгород"),
("Beslan", "Беслан"),
("Biysk", "Бийск"),
("Birobidzhan", "Биробиджан"),
("Blagoveshchensk", "Благовещенск"),
("Bologoye", "Бологое"),
("Bryansk", "Брянск"),
("Veliky Novgorod", "Великий Новгород"),
("Veliky Ustyug", "Великий Устюг"),
("Vladivostok", "Владивосток"),
("Vladikavkaz", "Владикавказ"),
("Vladimir", "Владимир"),
("Volgograd", "Волгоград"),
("Vologda", "Вологда"),
("Vorkuta", "Воркута"),
("Voronezh", "Воронеж"),
("Gatchina", "Гатчина"),
("Gdov", "Гдов"),
("Gelendzhik", "Геленджик"),
("Gorno-Altaysk", "Горно-Алтайск"),
("Grozny", "Грозный"),
("Gudermes", "Гудермес"),
("Gus-Khrustalny", "Гусь-Хрустальный"),
("Dzerzhinsk", "Дзержинск"),
("Dmitrov", "Дмитров"),
("Dubna", "Дубна"),
("Yeysk", "Ейск"),
("Yekaterinburg", "Екатеринбург"),
("Yelabuga", "Елабуга"),
("Yelets", "Елец"),
("Yessentuki", "Ессентуки"),
("Zlatoust", "Златоуст"),
("Ivanovo", "Иваново"),
("Izhevsk", "Ижевск"),
("Irkutsk", "Иркутск"),
("Yoshkar-Ola", "Йошкар-Ола"),
("Kazan", "Казань"),
("Kaliningrad", "Калининград"),
("Kaluga", "Калуга"),
("Kemerovo", "Кемерово"),
("Kislovodsk", "Кисловодск"),
("Komsomolsk-on-Amur", "Комсомольск-на-Амуре"),
("Kotlas", "Котлас"),
("Krasnodar", "Краснодар"),
("Krasnoyarsk", "Красноярск"),
("Kurgan", "Курган"),
("Kursk", "Курск"),
("Kyzyl", "Кызыл"),
("Leninogorsk", "Лениногорск"),
("Lensk", "Ленск"),
("Lipetsk", "Липецк"),
("Luga", "Луга"),
("Lyuban", "Любань"),
("Lyubertsy", "Люберцы"),
("Magadan", "Магадан"),
("Maykop", "Майкоп"),
("Makhachkala", "Махачкала"),
("Miass", "Миасс"),
("Mineralnye Vody", "Минеральные Воды"),
("Mirny", "Мирный"),
("Moscow", "Москва"),
("Murmansk", "Мурманск"),
("Murom", "Муром"),
("Mytishchi", "Мытищи"),
("Naberezhnye Chelny", "Набережные Челны"),
("Nadym", "Надым"),
("Nalchik", "Нальчик"),
("Nazran", "Назрань"),
("Naryan-Mar", "Нарьян-Мар"),
("Nakhodka", "Находка"),
("Nizhnevartovsk", "Нижневартовск"),
("Nizhnekamsk", "Нижнекамск"),
("Nizhny Novgorod", "Нижний Новгород"),
("Nizhny Tagil", "Нижний Тагил"),
("Novokuznetsk", "Новокузнецк"),
("Novosibirsk", "Новосибирск"),
("Novy Urengoy", "Новый Уренгой"),
("Norilsk", "Норильск"),
("Obninsk", "Обнинск"),
("Oktyabrsky", "Октябрьский"),
("Omsk", "Омск"),
("Orenburg", "Оренбург"),
("Orekhovo-Zuyevo", "Орехово-Зуево"),
("Oryol", "Орёл"),
("Penza", "Пенза"),
("Perm", "Пермь"),
("Petrozavodsk", "Петрозаводск"),
("Petropavlovsk-Kamchatsky", "Петропавловск-Камчатский"),
("Podolsk", "Подольск"),
("Pskov", "Псков"),
("Pyatigorsk", "Пятигорск"),
("Rostov-on-Don", "Ростов-на-Дону"),
("Rybinsk", "Рыбинск"),
("Ryazan", "Рязань"),
("Salekhard", "Салехард"),
("Samara", "Самара"),
("Saint Petersburg", "Санкт-Петербург"),
("Saransk", "Саранск"),
("Saratov", "Саратов"),
("Severodvinsk", "Северодвинск"),
("Smolensk", "Смоленск"),
("Sol-Iletsk", "Соль-Илецк"),
("Sochi", "Сочи"),
("Stavropol", "Ставрополь"),
("Surgut", "Сургут"),
("Syktyvkar", "Сыктывкар"),
("Tambov", "Тамбов"),
("Tver", "Тверь"),
("Tobolsk", "Тобольск"),
("Tolyatti", "Тольятти"),
("Tomsk", "Томск"),
("Tuapse", "Туапсе"),
("Tula", "Тула"),
("Tynda", "Тында"),
("Tyumen", "Тюмень"),
("Ulan-Ude", "Улан-Уде"),
("Ulyanovsk", "Ульяновск"),
("Ufa", "Уфа"),
("Khabarovsk", "Хабаровск"),
("Khanty-Mansiysk", "Ханты-Мансийск"),
("Chebarkul", "Чебаркуль"),
("Cheboksary", "Чебоксары"),
("Chelyabinsk", "Челябинск"),
("Cherepovets", "Череповец"),
("Cherkessk", "Черкесск"),
("Chistopol", "Чистополь"),
("Chita", "Чита"),
("Shadrinsk", "Шадринск"),
("Shatura", "Шатура"),
("Shuya", "Шуя"),
("Elista", "Элиста"),
("Engels", "Энгельс"),
("Yuzhno-Sakhalinsk", "Южно-Сахалинск"),
("Yakutsk", "Якутск"),
("Yaroslavl", "Ярославль");

INSERT INTO flights (from_place, to_place) VALUES
("Kemerovo", "Abakan"),
("Abakan", "Almetyevsk"),
("Kurgan", "Anadyr"),
("Rybinsk", "Anapa"),
("Blagoveshchensk", "Arkhangelsk"),
("Engels", "Astrakhan"),
("Syktyvkar", "Barnaul"),
("Gorno-Altaysk", "Belgorod"),
("Nizhnekamsk", "Beslan"),
("Yoshkar-Ola", "Birobidzhan"),
("Nalchik", "Biysk"),
("Novosibirsk", "Blagoveshchensk"),
("Nadym", "Bologoye"),
("Oktyabrsky", "Bryansk"),
("Lipetsk", "Chebarkul"),
("Yaroslavl", "Cheboksary"),
("Anapa", "Chelyabinsk"),
("Dzerzhinsk", "Cherepovets"),
("Vladimir", "Cherkessk"),
("Smolensk", "Chistopol"),
("Nazran", "Chita"),
("Ulyanovsk", "Dmitrov"),
("Ufa", "Dubna"),
("Izhevsk", "Dzerzhinsk"),
("Orekhovo-Zuyevo", "Elista"),
("Anadyr", "Engels"),
("Petrozavodsk", "Gatchina"),
("Ryazan", "Gdov"),
("Bryansk", "Gelendzhik"),
("Tyumen", "Gorno-Altaysk"),
("Ivanovo", "Grozny"),
("Sochi", "Gudermes"),
("Saint Petersburg", "Gus-Khrustalny"),
("Tobolsk", "Irkutsk"),
("Nizhnevartovsk", "Ivanovo"),
("Miass", "Izhevsk"),
("Chita", "Kaliningrad"),
("Murom", "Kaluga"),
("Chelyabinsk", "Kazan"),
("Gelendzhik", "Kemerovo"),
("Lyuban", "Khabarovsk"),
("Veliky Novgorod", "Khanty-Mansiysk"),
("Tula", "Kislovodsk"),
("Kursk", "Komsomolsk-on-Amur"),
("Cherepovets", "Kotlas"),
("Dubna", "Krasnodar"),
("Nizhny Novgorod", "Krasnoyarsk"),
("Samara", "Kurgan"),
("Kaluga", "Kursk"),
("Kazan", "Kyzyl"),
("Belgorod", "Leninogorsk"),
("Arkhangelsk", "Lensk"),
("Irkutsk", "Lipetsk"),
("Petropavlovsk-Kamchatsky", "Luga"),
("Voronezh", "Lyuban"),
("Novy Urengoy", "Lyubertsy"),
("Pyatigorsk", "Magadan"),
("Nakhodka", "Makhachkala"),
("Salekhard", "Maykop"),
("Gatchina", "Miass"),
("Zlatoust", "Mineralnye Vody"),
("Tambov", "Mirny"),
("Kyzyl", "Moscow"),
("Gudermes", "Murmansk"),
("Almetyevsk", "Murom"),
("Yelets", "Mytishchi"),
("Yessentuki", "Naberezhnye Chelny"),
("Norilsk", "Nadym"),
("Yeysk", "Nakhodka"),
("Tynda", "Nalchik"),
("Vladikavkaz", "Naryan-Mar"),
("Kotlas", "Nazran"),
("Beslan", "Nizhnekamsk"),
("Sol-Iletsk", "Nizhnevartovsk"),
("Barnaul", "Nizhny Novgorod"),
("Grozny", "Nizhny Tagil"),
("Novokuznetsk", "Norilsk"),
("Mirny", "Novokuznetsk"),
("Saransk", "Novosibirsk"),
("Biysk", "Novy Urengoy"),
("Yelabuga", "Obninsk"),
("Krasnodar", "Oktyabrsky"),
("Cheboksary", "Omsk"),
("Saratov", "Orekhovo-Zuyevo"),
("Naberezhnye Chelny", "Orenburg"),
("Obninsk", "Oryol"),
("Orenburg", "Penza"),
("Ulan-Ude", "Perm"),
("Omsk", "Petropavlovsk-Kamchatsky"),
("Astrakhan", "Petrozavodsk"),
("Birobidzhan", "Podolsk"),
("Makhachkala", "Pskov"),
("Khabarovsk", "Pyatigorsk"),
("Leninogorsk", "Rostov-on-Don"),
("Tver", "Ryazan"),
("Oryol", "Rybinsk"),
("Surgut", "Saint Petersburg"),
("Elista", "Salekhard"),
("Khanty-Mansiysk", "Samara"),
("Maykop", "Saransk"),
("Shatura", "Saratov"),
("Vladivostok", "Severodvinsk"),
("Veliky Ustyug", "Shadrinsk"),
("Yakutsk", "Shatura"),
("Severodvinsk", "Shuya"),
("Kaliningrad", "Smolensk"),
("Chebarkul", "Sochi"),
("Penza", "Sol-Iletsk"),
("Pskov", "Stavropol"),
("Moscow", "Surgut"),
("Komsomolsk-on-Amur", "Syktyvkar"),
("Rostov-on-Don", "Tambov"),
("Tolyatti", "Tobolsk"),
("Tomsk", "Tolyatti"),
("Yekaterinburg", "Tomsk"),
("Chistopol", "Tuapse"),
("Gdov", "Tula"),
("Lensk", "Tver"),
("Magadan", "Tynda"),
("Krasnoyarsk", "Tyumen"),
("Dmitrov", "Ufa"),
("Gus-Khrustalny", "Ulan-Ude"),
("Nizhny Tagil", "Ulyanovsk"),
("Podolsk", "Veliky Novgorod"),
("Mineralnye Vody", "Veliky Ustyug"),
("Naryan-Mar", "Vladikavkaz"),
("Vorkuta", "Vladimir"),
("Yuzhno-Sakhalinsk", "Vladivostok"),
("Perm", "Volgograd"),
("Vologda", "Vologda"),
("Luga", "Vorkuta"),
("Cherkessk", "Voronezh"),
("Tuapse", "Yakutsk"),
("Kislovodsk", "Yaroslavl"),
("Shuya", "Yekaterinburg"),
("Shadrinsk", "Yelabuga"),
("Volgograd", "Yelets"),
("Mytishchi", "Yessentuki"),
("Bologoye", "Yeysk"),
("Stavropol", "Yoshkar-Ola"),
("Lyubertsy", "Yuzhno-Sakhalinsk"),
("Murmansk", "Zlatoust");

SELECT id AS 'Номер рейса', c1.name AS 'Откуда', c2.name AS 'Куда'
FROM flights
JOIN cities AS c1
ON c1.label = flights.from_place 
JOIN cities AS c2
ON c2.label = flights.to_place
ORDER BY id;
